### ISSUE TITLE
support local LLM ?

### ISSUE THREAD

**Issue by tommy3266** [hpcaitech/SwiftInfer#4]
support local LLM ?

**Comment by FrankLeeeee** [comment]
Hi, may I know what you mean by `local LLM`?

**Comment by tommy3266** [comment]
@FrankLeeeee 

> Hi, may I know what you mean by `local LLM`?

Can I use your project to accelerate inference for my local large models?

**Comment by FrankLeeeee** [comment]
As long as you are able to run TensorRT locally, it would work.
