### ISSUE TITLE
Install Tensorrt_llm error: Could not find a version that satisfies the requirement tensorrt_llm==0.6.0 

### ISSUE THREAD

**Issue by Mokuroh0924** [hpcaitech/SwiftInfer#5]
I ran pip install . I got an error saying that I needed version 0.6.0 of tensorrt, but it doesn't seem to be available.
pip3 install tensorrt_llm==0.6.0 -U --extra-index-url https://pypi.nvidia.com
ERROR: Could not find a version that satisfies the requirement tensorrt_llm==0.6.0 (from versions: 0.5.0, 0.5.0.post1, 0.6.1, 0.7.0, 0.7.1)
ERROR: No matching distribution found for tensorrt_llm==0.6.0

**Comment by FrankLeeeee** [comment]
You need to build TRT-LLM from source.

**Comment by chaos318** [comment]
> You need to build TRT-LLM from source.

if build TRT-LLM from source v0.6.0. still can't build ,and will get an error : “ImportError: cannot import name 'LoraConfig' from 'tensorrt_llm.runtime.lora_manager' (/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/lora_manager.py)”。because LoraConfig is defined in v0.7.0。
and if use  TRT-LLM >= v0.7.0 will get another error : "AttributeError: 'LLaMAForCausalLM' object has no attribute 'get_transformer_layers" because SwiftInfer package have used get_transformer_layers。
 Could you Show me the bright way。

**Comment by FrankLeeeee** [comment]
Hi @chaos318 , I understand your frustration cuz the TensorRT-LLM APIs change too rapidly and it is difficult to install. We also encountered several cases like this during development as well. Thus, we tried to make it clear in our README, perhaps not clear enough though. 

To avoid the impact of rapidly changing APIs, we lock on a specific commit which is `42af740db51d6f11442fd5509ef745a4c043ce51`. During the development, this commit is the latest commit in the main branch and is corresponding to v0.6.0. 

```bash
git clone https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM
git checkout 42af740db51d6f11442fd5509ef745a4c043ce51

# do installation here
...
```

Then you need to build TensorRT-LLM from source as stated in the official documentation.

**Comment by chaos318** [comment]
> Hi @chaos318 , I understand your frustration cuz the TensorRT-LLM APIs change too rapidly and it is difficult to install. We also encountered several cases like this during development as well. Thus, we tried to make it clear in our README, perhaps not clear enough though.
> 
> To avoid the impact of rapidly changing APIs, we lock on a specific commit which is `42af740db51d6f11442fd5509ef745a4c043ce51`. During the development, this commit is the latest commit in the main branch and is corresponding to v0.6.0.
> 
> ```shell
> git clone https://github.com/NVIDIA/TensorRT-LLM.git
> cd TensorRT-LLM
> git checkout 42af740db51d6f11442fd5509ef745a4c043ce51
> 
> # do installation here
> ...
> ```
> 
> Then you need to build TensorRT-LLM from source as stated in the official documentation.

ok多谢

**Comment by FrankLeeeee** [comment]
> > Hi @chaos318 , I understand your frustration cuz the TensorRT-LLM APIs change too rapidly and it is difficult to install. We also encountered several cases like this during development as well. Thus, we tried to make it clear in our README, perhaps not clear enough though.
> > To avoid the impact of rapidly changing APIs, we lock on a specific commit which is `42af740db51d6f11442fd5509ef745a4c043ce51`. During the development, this commit is the latest commit in the main branch and is corresponding to v0.6.0.
> > ```shell
> > git clone https://github.com/NVIDIA/TensorRT-LLM.git
> > cd TensorRT-LLM
> > git checkout 42af740db51d6f11442fd5509ef745a4c043ce51
> > 
> > # do installation here
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then you need to build TensorRT-LLM from source as stated in the official documentation.
> 
> ok多谢

@chaos318 My pleasure.
